version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: TextQueries
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 228337
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: TextQueries
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 228337

volumes:
  postgres_data:
